version: '3.9'

services:
    neo4j:
        container_name: neo4j
        restart: always
        image: neo4j:latest
        # user: "1001:1001"
        volumes:
          - /neo4j/data:/data 
          - /neo4j/logs:/logs 
          - /neo4j/import:/var/lib/neo4j/import 
          - /neo4j/plugins:/plugins
          - /neo4j/dumps:/dumps/neo4j 
        ports:
          - "7474:7474"
          - "7687:7687"
        env_file:
          - .env
        networks:
          - db_comm

    update:
        container_name: update
        restart: always
        volumes:
          - ./info.log:/setup/info.log
        build: .
        env_file:
          - .env
        networks:
          - db_comm

networks:
  db_comm:
    driver: bridge
    ipam:
      driver: default