version: '3.9'

services:
    neo4j:
        container_name: neo4j
        restart: always
        image: neo4j:latest
        # user: "1001:1001"
        volumes:
          - /neo4j/data:/data 
          - /neo4j/logs:/logs 
          - /neo4j/import:/var/lib/neo4j/import 
          - /neo4j/plugins:/plugins 
        ports:
          - "7474:7474"
          - "7687:7687"
        env_file:
          - .env

    update:
        container_name: update
        restart: always
        volumes:
          - ./log.txt:/setup/log.txt
        ports: 
          - "7687:7687"
        build: .
        env_file:
          - .env