version: '3.9'

networks:
    web:
        external: true

services:
    neo4j:
        container_name: neo4j
        restart: always
        image: neo4j:latest
        volumes:
          - $HOME/data/neo4j/data:/data 
          - $HOME/data/neo4j/logs:/logs 
          - $HOME/data/neo4j/import:/var/lib/neo4j/import 
          - $HOME/data/neo4j/plugins:/plugins 
        ports:
          - "7474:7474"
          - "7687:7687"
        environment:
          - NEO4J_AUTH=neo4j/test
        networks:
            - web
    
    mms:
        container_name: mms
        restart: always
        build: .
        networks:
            - web